openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'Photographer'
  contact:
    email: 'Denis.Rokker@gmail.com'
paths:
  '/accounts/sign-up':
    post:
      description: registration
      requestBody:
        description: Initial registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
                - Password
              properties:
                Email:
                  type: string
                Password:
                  type: string
      responses:
        200:
          description: Sucsessful registration
          content:
            application/json:
              schema:
                type: object
                required:
                  - Token
                properties:
                  Token:
                    type: string
        400:
          description: Error. `Email or password` is empty
          content:
            application/json:
              schema:
                type: object
                required:
                  - Email or password is empty
                properties:
                  Email or password is empty:
                    type: string
  '/accounts/sign-in':
    post:
      description: Enter
      requestBody:
        description: Input data entry
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
                - Password
              properties:
                Email:
                  type: string
                Password:
                  type: string
      responses:
        200:
          description: successful login
          content:
            application/json:
              schema:
                type: object
                required:
                  - Token
                properties:
                  Token:
                    type: string
        400:
          description: Error. Account does not exist
          content:
            application/json:
              schema:
                type: object
                required:
                  - Account does not exist
                properties:
                  Account does not exist:
                    type: string
  '/accounts/sign-out':
    delete:
      description: exit
      parameters:
        - in: header
          name: X-Auth-Token
          schema:
            type: string
          required: true
      responses:
        204:
          description: exit
  '/accounts/id':
    get:
      description: getting user information
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - $ref: '#/components/parameters/X-Auth-Token'
      responses:
        200:
          description: providing user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: integer
                  Email:
                    type: string
  '/events/':
    post:
      description: create new events
      requestBody:
        description: event structure filling
        required: true
        content:
          aplication/json:
            schema:
              type: object
              required:
                - Name
                - Description
                - OwnerID
                - Timelines
              properties:
                Name:
                  type: string
                Description:
                  type: string
                OwnerID:
                  type: integer
                Timelines:
                  type: array
                  items:
                    type: object
      responses:
        200:
          description: completion of the event
  '/events/id':
    put:
      description: update information for ivents
      requestBody:
        description: event structure update
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Name
                - Timelines
                - Description
              properties:
                Name:
                  type: string
                Description:
                  type: string
                Timelines:
                  type: array
                  items:
                    type: object
      responses:
        204:
          description: event update completion
  '/offers':
    post:
      description: create offer
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        description: account id and event id
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - AccountID
                - EventID
              properties:
                AccountID:
                  type: integer
                EventID:
                  type: integer
      responses:
        200:
          description: offer data
          content:
            application/json:
              schema:
                type: object
                required:
                  - ID
                  - AccountID
                  - EventID
                  - Created
                  - Updated
                properties:
                  ID:
                    type: integer
                  AccountID:
                    type: integer
                  EventID:
                    type: integer
                  Created:
                    type: string
                    format: date-time
                  Update:
                    type: string
                    format: date-time
  '/offers/id':
    put:
      description: offer data update
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      requestBody:
        description: event approval
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - IsApproved
              properties:
                IsApproved:
                  type: integer
                  nullable: true
      responses:
        200:
          description: updated offer data
          content:
            application/json:
              schema:
                type: object
                required:
                  - ID
                  - AccountID
                  - EventID
                  - IsApproved
                  - Created
                  - Update
                properties:
                  ID:
                    type: integer
                  AccountID:
                    type: integer
                  EventID:
                    type: integer
                  IsApproved:
                    type: integer
                    nullable: true
                  Created:
                    type: string
                    format: date-time
                  Update:
                    type: string
                    format: date-time
    delete:
      description: delete offer
      parameters:
        - $ref: '#/components/parameters/X-Auth-Token'
      responses:
        200:
          description: delete offer
components:
  parameters:
    X-Auth-Token:
      in: header
      name: X-Auth-Token
      description: Authentication Token
      schema:
        type: string
      required: true
      example: "njxa7uLl3AYSkseDY61KlYJ+FJ0TrRqhVJOhaj4BYHQ="
        